[package]
name = "material-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { version = "1.23.1", features = ["derive", "must_cast"] }
material-colors = "0.4.2"
taffy = "0.8.3"
