[package]
name = "material-sdl2-renderer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
font-kit = "0.14.3"
material-core.workspace = true
ouroboros = "0.18.5"
sdl2 = { version = "0.37.0", features = ["ttf"] }
